### ISSUE TITLE
Overlaying workspace feedback

### ISSUE THREAD

**Issue by breandan** [duckietown/sim-duckiebot-lanefollowing-demo#11]
Nice work on the workspace overlaying, this was a good idea. Some early feedback: after walking through the [new documentation](http://docs.duckietown.org/DT18/AIDO/out/ros_baseline.html#sub:autoid-DO-NOT-USE-THIS-VERY-UNSTABLE-LINK-28914b9a-39) with @maivincent, we encountered two issues. 

- [x] First, we needed to run `docker-compose -f docker-compose-lf.yml build` in order to rebuild the Dockerfiles - it would be helpful to mention this somewhere in the documentation.

- [x] Second and more problematically, we were unable to add a node using the `roslaunch` [configuration method](http://wiki.ros.org/roslaunch/XML/node), i.e. by adding a `<node.../>` tag to the `lf_slim.launch` file (since the `lanefollow` container does not have access to the recompiled catkin artifacts, and thus cannot find the [`dt_dependent_node` referenced in `lf_slim.launch`](https://github.com/duckietown/sim-duckiebot-lanefollowing-demo/blob/bbc715d1aee305973abc93d8609e28919d48e772/lf_slim.launch#L81) file, even though we added the `dt_dependent_node` and its enclosing package to the project directory).

- [x] While we were able to use the [`rosrun` command to start a node](https://github.com/duckietown/sim-duckiebot-lanefollowing-demo/blob/bbc715d1aee305973abc93d8609e28919d48e772/docker-compose-lf.yml#L70), after several variations of modifying the `docker-compose-lf.yml` file, we ran out of ideas for configuring the `roslaunch` file with the `dt_dependent_node` placeholder.

- [x] We figured the documentation could use a few more cycles to make this workflow a bit clearer - as we discussed this afternoon, a guide on how to copy a package from the `duckietown/software` repository would be a helpful addition. Please let Vincent or I know if you need any help or further details. Thank you.

**Comment by bhairavmehta95** [comment]
Sure, thanks for putting this up here. Chances are I don't get to this tonight (maybe just work on it during the day tomorrow)

**Comment by bhairavmehta95** [comment]
Ah. Actually, the second issue has a really quick fix. Really, all it is that your custom nodes will just get a separate launch file. 

Really, what should be happening is that DockerfileLFSlim and DockerfileCatkin need to be combined. LFSlim is an artifact from the previous iteration, but as you can see, it just copies the launch file and runs it. Really, since now that's the main node, it should all be in one. Again, thank you for the suggestions.

**Comment by bhairavmehta95** [comment]
~Reopening until documentation is fixed~ (Fixed), and we have an example of how to add a node from duckietown source. But, now that the launch file works, shouldn't be too much work.

**Comment by bhairavmehta95** [comment]
Fully done - node and documentation in, launch file edited!
