### ISSUE TITLE
Docker network not found error

### ISSUE THREAD

**Issue by brian-h-wang** [duckietown/sim-duckiebot-lanefollowing-demo#5]
I'm trying to use this simulator for the AIDO lane following challenge and am running into some trouble. When I run this command from the readme:

`docker run --entrypoint=qemu3-arm-static --network=gym-duckietown-net -it duckietown/rpi-duckiebot-base:master18 /bin/bash`

I get the following error message:

`docker: Error response from daemon: network gym-duckietown-net not found`

This is after running the docker-compose command from the readme in a separate terminal window.

Also, the rosbag file from rosmonitor does not seem to be writing. Any advice on how to fix these issues? I’m new to using docker, and would appreciate some help.

I’m running all of this on an Ubuntu 16.04 computer, with ROS kinetic installed.

Thanks very much for your help!

**Comment by breandan** [comment]
Re: Error message. Have you tried `docker network create gym-duckietown-net`? We may need to update the README, thanks for reporting. Will investigate the rosbag issue shortly.

**Comment by breandan** [comment]
Re: `rosbag`. I was unable to reproduce the issue as described. The `rosmonitor` container writes to `/home/rosbag/full.bag` on Ubuntu 18.04.1 LTS. On Mac OS X or Windows, you might need to create this directory, or share a different one that Docker has access to, by modifying [this line](https://github.com/duckietown/sim-duckiebot-lanefollowing-demo/blob/e8546d6aa8f1aaf1426fab2b7f5fdf92b875d1e2/docker-compose-lf.yml#L60) (before the colon), specifying the path where you want the bag to be written on your machine. Can you provide any more details about your system in order to help us troubleshoot? Thanks!

**Comment by bhairavmehta95** [comment]
Re: `network not found`. 

So the way this network gets created is in the `docker-compose` file, so are you making sure to run 

`docker-compose -f docker-compose-lf.yml pull && compose -f docker-compose-lf.yml up`

before running the `docker run --entrypoint=qemu3-arm-static --network=gym-duckietown-net -it duckietown/rpi-duckiebot-base:master18 /bin/bash` command?

**Comment by breandan** [comment]
Re: `network not found`.

I was unable to reference the network `gym-duckietown-net`, [defined in the `docker-compose-lf.yml` file](https://github.com/duckietown/sim-duckiebot-lanefollowing-demo/blob/e8546d6aa8f1aaf1426fab2b7f5fdf92b875d1e2/docker-compose-lf.yml#L66), using the command line form of `docker run ...` as described in [the readme](https://github.com/duckietown/sim-duckiebot-lanefollowing-demo#via-docker-in-real-time). After first running `docker network create gym-duckietown-net`, doing `docker-compose -f docker-compose-lf.yml pull && compose -f docker-compose-lf.yml up`, then starting the `duckietown/rpi-duckiebot-base:master18` container, everything worked as expected.

**Comment by bhairavmehta95** [comment]
@breandan  I can fix the readmes - but isn't the `docker-compose` supposed to take care of creating the network?

**Comment by bhairavmehta95** [comment]
@breandan should I add that to the README? I always thought the docker-compose would take care of the network creation, because this `gym-duckietown-net` was specified in the original gym-duckietown-agent, but never actually created by the user?

**Comment by breandan** [comment]
> @breandan I can fix the readmes - but isn't the docker-compose supposed to take care of creating the network?

I believe the behavior may vary depending on which version of Docker the user is running - the default scope for networks defined in `docker-compose*.yml` may have changed in a recent release. FWIW I also encountered this issue running Docker version `18.06.1-ce build e68fc7a`.

**Comment by bhairavmehta95** [comment]
Hmm okay. So I will update the readmes to fix this, since your instructions seem to cover both cases. Thank you both!

**Comment by bhairavmehta95** [comment]
Hmm okay. So I will update the readmes to fix this, since your instructions seem to cover both cases. Thank you both!
