### ISSUE TITLE
Compatibility with OS X ?

### ISSUE THREAD

**Issue by liampaull** [duckietown/sim-duckiebot-lanefollowing-demo#6]
I got this error on OS X when I ran `docker network create gym-duckietown-net && docker-compose -f docker-compose-lf.yml pull && docker-compose -f docker-compose-lf.yml up` - is it an OS related problem:

```
Creating sim-duckiebot-lanefollowing-demo_rosmonitor_1            ... error
Creating sim-duckiebot-lanefollowing-demo_gym-duckietown-ros_1    ... 

ERROR: for sim-duckiebot-lanefollowing-demo_rosmonitor_1  Cannot start service rosmonitor: b'Mounts denied: \r\nThe path /home/rosbag\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.comCreating sim-duckiebot-lanefollowing-demo_gym-duckietown-ros_1    ... done

ERROR: for rosmonitor  Cannot start service rosmonitor: b'Mounts denied: \r\nThe path /home/rosbag\r\nis not shared from OS X and is not known to Docker.\r\nYou can configure shared paths from Docker -> Preferences... -> File Sharing.\r\nSee https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.\r\n.'
ERROR: Encountered errors while bringing up the project.
```

If yes we should at least specify that this is not supported for OS X

**Comment by bhairavmehta95** [comment]
On OSX, does the directory /home/ exist?

https://docs.docker.com/docker-for-mac/osxfs/#namespaces

@liampaull would you mind changing the docker-compose.yml file, where it says:

`home/rosbag:/home/rosbag` to `/tmp/rosbag:/tmp/rosbag`. It seems like on osx, the `/home` directory is not by default accessible to mounting.

**Comment by liampaull** [comment]
good
